### ISSUE TITLE
draw_feature_importance plot for classification is not working

### ISSUE THREAD

**Issue by ManuelSpinola** [ModelOriented/forester#103]
draw_feature_importance(train_output$best_models, train_output$test_data, train_output$y)

Error in test_explainer(explainer, has_data = TRUE, has_y = TRUE, function_name = "model_parts") :
The model_parts function requires an object created with explain() function.

**Comment by HubertR21** [comment]
The issue should be already resolved in the 1.2.0 version of the package.
