### ISSUE TITLE
Code error in Usage example

### ISSUE THREAD

**Issue by Oliver-CISC** [ModelOriented/forester#15]
In **README.md** the following code throws an error due to the type being set to 'regression' rather than 'classification'

`best_model <- forester(data = titanic, target = "survived", type = "regression",
      		                       metric = "precision", tune = FALSE)`

Error:
`__________________________
FORESTER
Error in check_conditions(data, target, type) : 
  Program is stopped. The class of target column is factor, not appropriate for regression problem`

**Comment by kozaka93** [comment]
Thank you. Fix in #12.
