### ISSUE TITLE
allow for custom metrics

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/forester#24]
It would be useful to pass a custom `metric`/`tune_metric` (R function) to `forester()` etc. instead of only a predefined character.

**Comment by lhthien09** [comment]
We will think of allowance for `loss_function()` argument.

**Comment by kozaka93** [comment]
Thank you. We have made major changes to the forester package. The previous version of the package is available on the [`old`](https://github.com/ModelOriented/forester/tree/old) branch. It will not be supported, we encourage you to use the new one.
