### ISSUE TITLE
should the best model from `forester` preserve an information about the train:test split?

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/forester#29]
This seems kinda important: only `best_model` is returned without knowing for which `train:test` split.

**Comment by lhthien09** [comment]
Hi, we should think of that. In [forester](https://github.com/ModelOriented/forester/blob/main/R/forester.R), line 57, we use the function [split_data](https://github.com/ModelOriented/forester/blob/main/R/split_data.R) with default ratio = 0.8, however `split_data` allows user to plug in ratio of splitting train-test. We will add this parameter of splitting train-test into main function `forester`.

**Comment by lhthien09** [comment]
new argument train_ratio was added to [forester.R](https://github.com/ModelOriented/forester/blob/main/R/forester.R)

Reference to: lines 50, 58.

**Comment by hbaniecki** [comment]
Thanks @lhthien09! Great feature.
My initial issue was about not saving the ids of splits in the final (returned) object. Meaning the user can't know what were the splits.
