### ISSUE TITLE
Be careful when converting factor target variable (to a negative factor?)

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/forester#30]
I use a `factor`-encoded target variable with `"0"/"1"` and this type of coercion looks weird:

![image](https://user-images.githubusercontent.com/32574004/141653045-9e23fd11-c59a-41f4-855a-60c2f97a319f.png)

**Comment by lhthien09** [comment]
References: lines 84 -> 94 in [check_conditions.R](https://github.com/ModelOriented/forester/blob/main/R/check_conditions.R)
