### ISSUE TITLE
Error: Failed to install 'forester' from GitHub

### ISSUE THREAD

**Issue by VladPerervenko** [ModelOriented/forester#32]
`devtools::install_github("ModelOriented/forester")
Downloading GitHub repo ModelOriented/forester@HEAD
Error: Failed to install 'forester' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE`

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

**Comment by lhthien09** [comment]
Hi, thank you for your report. I think the problem may come from some libraries do not work well in the newest R version.  {forester} team will check and inform you soon.
![image](https://user-images.githubusercontent.com/56301506/145729032-3c7e50bf-8cda-4075-addc-c66d545465fd.png)

**Comment by lhthien09** [comment]
@VladPerervenko Hi, we made some changes in {forester} and now, it should work. Please feel free to report issue if you still meet this problem.

**Comment by VladPerervenko** [comment]
This error is not only generated by this library. Obviously a problem on my part. Couldn't find a reason.
`> remotes::install_github("ModelOriented/forester")
Downloading GitHub repo ModelOriented/forester@HEAD
Error: Failed to install 'forester' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE`
