### ISSUE TITLE
model_performance()

### ISSUE THREAD

**Issue by lhthien09** [ModelOriented/forester#34]
After training models, {forester} couldn't find function model_performance(), which is later used to display a table of performance comparison over different metrics.

**Comment by matteodefelice** [comment]
same issue here, just installed.

**Comment by lhthien09** [comment]
Hi, it happened for a line of code in evaluate.R whilst we did not run the DALEX package. The function [model_performance()](https://www.rdocumentation.org/packages/DALEX/versions/2.3.0/topics/model_performance) is from DALEX.
Solution: I specified DALEX::model_performance() in evaluate.R. Hope that after reinstalling the package, it will go smoothly.
