### ISSUE TITLE
run forester parallel

### ISSUE THREAD

**Issue by felipe-mansoldo** [ModelOriented/forester#35]
Hello,
congratulations on developing this package.
is there any way to run in parallel? my database is very big and I need to use many cores..
thanks

**Comment by lhthien09** [comment]
@felipe-mansoldo thank you for your suggestion. Some boosting algorithms inside {forester} require multi-core running. {forester} team will consider about it in near future.

**Comment by Tripartio** [comment]
Is there any progress on this? As of September 2023,  it seems that forester still does not use any parallel processing. Parallel processing is an essential feature for any AutoML procedure.
