### ISSUE TITLE
How to save the better model?

### ISSUE THREAD

**Issue by Leprechault** [ModelOriented/forester#38]
How do I save the better model after forester analysis finished to disk so that I can load it at a later time? I'd like to use `save()` and `load()` or `saveRDS()` or `readRDS()` functions. It is possible?

In my case, I make:

```
# Build the model pipeline
cc_model_complete <- forester::forester(data = RES_sel_vars,
                           target = "cc",
                           type = "regression")
# COMPARISON
# Results of compared models:
# model            rmse         mse          r2         mad
# ---------  ----------  ----------  ----------  ----------
# Ranger      0.0480812   0.0023118   0.9005513   0.0266172
# Catboost    0.0776190   0.0060247   0.7408305   0.0454772
# XGboost     0.0839399   0.0070459   0.6969006   0.0493881
# LightGBM    0.0928959   0.0086296   0.6287718   0.0540686
# The best model based on rmse metric is Ranger.
```
and I'd like to save the better model inside the object `cc_model_complete`.

Thanks in advance,

Alexandre

**Comment by lhthien09** [comment]
Hi, `saveRDS()` and `readRDS()` work well in saving and retrieving outcome model from {forester} for later use. Since returned model is an R object.
