### ISSUE TITLE
Returning the predicted values and performance metrics for forester()

### ISSUE THREAD

**Issue by mcavs** [ModelOriented/forester#42]
The forester() returns only predictive values and performance measures for the best performing model. It can do this optionally for other models. In this way, users may use these for comparison studies.

**Comment by kozaka93** [comment]
Thank you. We have made major changes to the forester package. The previous version of the package is available on the [`old`](https://github.com/ModelOriented/forester/tree/old) branch. It will not be supported, we encourage you to use the new one.
