### ISSUE TITLE
classification doesn't work with numeric target vector: 0, 1

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/forester#51]
![image](https://user-images.githubusercontent.com/32574004/202198960-8473ada7-3b09-446d-a436-38644d539b43.png)

**Comment by mikolajsp** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b641427b-8d18-494c-b15a-b1605a997673/Untitled.png)

Also doesn't work for target vector as strings
