### ISSUE TITLE
Check data errors when a column contains only one unique value

### ISSUE THREAD

**Issue by mikolajsp** [ModelOriented/forester#54]
![image](https://user-images.githubusercontent.com/55801784/202201321-aaeed23c-6b77-4d4e-a907-b55d46deed13.png)

column with `sd = 0` throws error when put into the `check_data()` function .

Possibly it is checked later, but this throws an error for calculating correlation

**Comment by HubertR21** [comment]
@mikolajsp Can you provide the data set which lead to an error?

**Comment by mikolajsp** [comment]
I think it was this one https://www.kaggle.com/datasets/fedesoriano/stellar-classification-dataset-sdss17
