### ISSUE TITLE
Month number in the timestamp of file created by save()

### ISSUE THREAD

**Issue by wi1lku** [ModelOriented/forester#58]
![obraz](https://user-images.githubusercontent.com/72528194/202202939-a97a86ae-a7db-460e-823c-cb0f0946327b.png)
![obraz](https://user-images.githubusercontent.com/72528194/202202974-8b06cf50-cbee-46a5-aaca-ffe58ef55e26.png)

**Comment by PSlowakiewicz** [comment]
Fix in #80
