### ISSUE TITLE
label must be provided when data is a matrix - XGBoost

### ISSUE THREAD

**Issue by RickPack** [ModelOriented/forester#96]
This causes XGBoost to return:
`Error in xgb.get.DMatrix(data, label, missing, weight, nthread = merged$nthread) : 
  label must be provided when data is a matrix`

Using economics from the ggplot2 package:

```
library(forester)
library(ggplot2)

test_model <-
  train(
    data.frame(economics) %>% select(-date),
    type = 'regression',
    y = 'uempmed',
    engine = c('xgboost'))

```

**Comment by RickPack** [comment]
The error is defined in the R source code for XGboost here:
https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.DMatrix.R
`# get dmatrix from data, label
# internal helper method
xgb.get.DMatrix <- function(data, label = NULL, missing = NA, weight = NULL, nthread = NULL) {
  if (inherits(data, "dgCMatrix") || is.matrix(data)) {
    if (is.null(label)) {
      stop("label must be provided when data is a matrix")
    }`

**Comment by HubertR21** [comment]
As mentioned in Issue #97 we've already found a solution for that problem
